### ISSUE TITLE
Unityバージョン決定

### ISSUE THREAD

**Issue by akai-inu** [punity/punity-client#1]
現在最新

- >= 5.4.0f3
- < 5.5.0

でOK?

**Comment by ike-jp** [comment]
現状どれが安定しているか等分からないので

+ >= 5.4.0f3
+ < 5.5.0

で問題なさそうであればOKです～。
１つに決め打ちしなくて大丈夫ですかね？

Unityほどのエンジンであれば問題ないのかな・・・
5.5.0はベータ版ですよね？プロジェクトとして最新を追うのか、
安定を追うのかを決めておいたほうがよさそうな気がしました。

開発は安定版でやりたいですが、開発途中に最新リリースがあったら
適宜更新するかも決めておきたいです。

**Comment by ike-jp** [comment]
https://github.com/punity/punity-client/issues/2
の理由からとりあえず固定バージョンの方が良いのかなと思いました。

Unityレベルのエンジンが急にUI変えたりすることは流石にないですかね・・・

**Comment by ike-jp** [comment]
今実際にググってみて勘違いに気づきました。

+ >= 5.4.0f3
+ < 5.5.0

マイナーバージョンが上がらないければ適宜アップデートってことですね。
それでOKです。上記確定で。

問題なければクローズしてください。

**Comment by ike-jp** [comment]
[環境構築と開発準備](https://github.com/punity/punity-client/wiki/%E7%92%B0%E5%A2%83%E6%A7%8B%E7%AF%89%E3%81%A8%E9%96%8B%E7%99%BA%E6%BA%96%E5%82%99)に反映

**Comment by akai-inu** [comment]
何かしらバージョン差異で問題でたら特定バージョンに統一するってことで、インストール時の最新でいいのではないだろうか。ということでその点追記してclose
